name: phantom_deeplink_app
description: An unofficial Flutter demo app for Phantom wallet deeplink integration

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and state management
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  
  # Deeplink and URL handling
  url_launcher: ^6.2.4
  app_links: ^4.0.1
  
  # Crypto and encoding
  crypto: ^3.0.3
  convert: ^3.1.1
  
  # HTTP requests
  http: ^1.1.2
  
  # Local storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
